#!/bin/bash

set -o nounset
#set -o errexit
XMLTV=/srv/media/xmltv
curl=/opt/puppetlabs/puppet/bin/curl
TMPFILE=/tmp/$(basename $0).routes.$$
ROUTES=/etc/openvpn/client/iptv.routes
URL="http://cdn.thebesthost.uk:80/get.php?username=hhtzoznu&password=q53UWdm5g&output=ts&type=m3u_plus"

echo route-nopull > ${TMPFILE}
${curl} -s "${URL}" |
  egrep '^http:' | 
  egrep -v '/series/|/movie/' |
  sed 's/\r//' |
  while read CHANNEL
  do
    echo ${CHANNEL} | sed -n 's;^http://\(.*\):.*$;\1;p' 
    ${curl} -v -s "${CHANNEL}" -o /dev/null  --max-time 5 2>&1 |
      sed -n -e 's;.*Location: http://\(.*\):.*$;\1;p' 
  done |
    sed -e 's/^/route /p' |
    sort -u >> ${TMPFILE}

# Restart clients if changed
if ! diff ${ROUTES} ${TMPFILE}
then
  cp ${TMPFILE} ${ROUTES}
  #openpyn uk -d -o "$(cat ${ROUTES} | sed 's/^/--/' | tr '\n' ' ')"
  systemctl restart openvpn-client@nordvpn
  sleep 10
  systemctl status oopenvpn-client@nordvpn
fi

rm ${TMPFILE} 2>/dev/null || true

# vim: nu sw=2 ai
