#!/bin/bash

set -o nounset
#set -o errexit
XMLTV=/srv/media/xmltv
curl=/opt/puppetlabs/puppet/bin/curl
TMPFILE=/tmp/$(basename $0).$$
ROUTES=/etc/openvpn/client/iptv.routes

{
  sed -n 's;^http://\(.*\):.*$;\1;p' ${XMLTV}/*.m3u  | sort -u
  sed -n '/^http:/p'  ${XMLTV}/*.m3u  | 
  sed -e 's/\r//' |
    while read URL
    do
      ${curl} -v -s ${URL} -o /dev/null  --max-time 5 2>&1 | sed -n 's;.*Location: http://\(.*\):.*$;\1;p'
    done | sort -u
} | sed 's/^/route /' > ${TMPFILE}

# Restart clients
if diff ${ROUTES} ${TMPFILE}
then
  cp ${TMPFILE} ${ROUTES}
  systemctl restart openvpn-client*
  sleep 5
  systemctl status openvpn-client*
fi

rm ${TMPFILE}

# vim: nu sw=2 ai
