#!/usr/bin/env bash

#set -o nounset
#set -o errexit

LOGLEVEL=${LOGLEVEL:-"INFO"}

# shellcheck disable=1090
source "$(dirname "${0}")"/../functions/log.sh

curl=/opt/puppetlabs/puppet/bin/curl
DATA=$(dirname "$0")/iptv_urls
if [[ -f "${DATA}" ]]
then
  # shellcheck source=/dev/null
  . "${DATA}"
else
  echo "URL file ${DATA} not found" >&2
  exit 1
fi

PLEX_SERVER="tango.theclarkhome.com"
get_dvr_id() {
  ${curl} --silent "http://${PLEX_SERVER}:32400/livetv/dvrs?X-Plex-Token=${PLEX_TOKEN}" \
    | xml2 \
    | grep /MediaContainer/Dvr/@key | cut -f 2 -d '='
}

DVR_ID=$(get_dvr_id)

log_debug "Update plex guide at token ${PLEX_TOKEN}"
[[ ! -z ${PLEX_TOKEN} ]] &&
  ${curl} --silent --request POST "http://${PLEX_SERVER}:32400/livetv/dvrs/${DVR_ID}/reloadGuide?X-Plex-Token=${PLEX_TOKEN}"
res=$?
log_debug "Update plex guide returned ${res}"
