#!/bin/bash

set -o nounset
#set -o errexit
XMLTV=/srv/media/xmltv

URL="http://vmdirect.co.uk/get.php?username=hhtzoznu&password=q53UWdm5g&type=m3u_plus&output=ts"

channel=
sedscript=

# channels to deleted
while read -r pattern
do
    sedscript+="/$pattern/,+1 d;"
done <<EOF
group-title="VOD
M4v
group-title="UK: International"
group-title="Romanian Channels"
group-title="Spain channels"
group-title="Spain Channels"
group-title="Albanian"
group-title="XXX"
group-title="Portuguese Channels"
group-title="De channels"
group-title="Netherlands channels"
group-title="Scandinavian Channels"
group-title="EX-YU"
group-title="World Streams"
group-title="Spain channels"
group-title="France Channels"
group-title="Italian Channels"
group-title="Arabic Channels"
group-title="Turkish Channels"
group-title="USA Channels"
group-title="3 o'clock Kick Off's"
tvg-name="Tape
group-title=""
group-title="Narcos"
group-title="TvSeries
EOF

#tvg-id="" tvg-name="BBC1 HD 1080\*"~tvg-id="BBC1London.uk" tvg-name="UK BBC 1 HD"
#tvg-id="" tvg-name="BBC2 HD 1080\*"~tvg-id="BBC2.uk" tvg-name="UK BBC 2"
#tvg-id="" tvg-name="ITV2 HD 1080\*"~tvg-id="ITV2.uk" tvg-name="UK ITV 2"
#tvg-id="" tvg-name="ITV3 HD 1080\*"~tvg-id="ITV3.uk" tvg-name="UK ITV 3"
#tvg-id="" tvg-name="ITV4 HD 1080\*"~tvg-id="ITV4.uk" tvg-name="UK ITV 4"
#tvg-id="" tvg-name="ITV HD 1080\*"~tvg-id="ITV1London.uk" tvg-name="UK ITV 1"
#tvg-id="" tvg-name="UK: Sky Living HD 1080\*"~tvg-id="" tvg-name="Sky Living"
# channels to be mapped
while IFS='~' read -r pattern1 pattern2
do
    sedscript+="s~$pattern1~$pattern2~;"
done <<EOF
tvg-id="" tvg-name="BBC NEWS HD 1080\*"~tvg-id="" tvg-name="UK BBC NEWS"
tvg-id="" tvg-name="BBC FOUR HD 1080\*"~tvg-id="BBC4.uk" tvg-name="UK BBC 4"
tvg-id="" tvg-name="Channel 4 HD 1080\*"~tvg-id="Channel4.uk" tvg-name="UK Channel 4"
tvg-id="" tvg-name="Channel 5 HD 1080\*"~tvg-id="Channel5.uk" tvg-name="UK Channel 5"
tvg-id="" tvg-name="E4 HD 1080\*"~tvg-id="E4.uk" tvg-name="UK E4"
tvg-id="" tvg-name="Film4 HD 1080\*"~tvg-id="Film4.uk" tvg-name="UK Film 4"
tvg-id="" tvg-name="More4 HD 1080\*"~tvg-id="More4.uk" tvg-name="More 4"
tvg-id="" tvg-name="Sky Cinema Action & Adventure HD 1080\*"~tvg-id="SkyMoviesActionThriller.uk" tvg-name="Sky Movies Action and Adventure HD"
tvg-id="" tvg-name="Sky Cinema Comedy HD 1080\*"~tvg-id="SkyMoviesComedy.uk" tvg-name="Sky Movies Comedy HD"
tvg-id="" tvg-name="Sky Cinema Crime & Thriller HD 1080\*"~tvg-id="SkyCinemaThriller.uk" tvg-name="Sky Movies Crime and Thriller HD"
tvg-id="" tvg-name="Sky Cinema Disney HD 1080\*"~tvg-id="SkyMoviesDisney.uk" tvg-name="Sky Movies Disney HD"
tvg-id="" tvg-name="Sky Cinema Drama & Romance HD 1080\*"~tvg-id="SkyMoviesDrama.uk" tvg-name="Sky Movies Drama and Romance HD"
tvg-id="" tvg-name="Sky Cinema Family HD 1080\*"~tvg-id="SkyMoviesFamily.uk" tvg-name="Sky Movies Family HD"
tvg-id="" tvg-name="Sky Cinema Greats HD 1080\*"~tvg-id="Sky Movies Greats UK" tvg-name="Sky Movies Modern Greats HD"
tvg-id="" tvg-name="Sky Cinema Hits HD 1080\*"~tvg-id="SkyCinemaHits.uk " tvg-name="Sky Cinema Hits HD"
tvg-id="" tvg-name="Sky Cinema Premiere HD 1080\*"~tvg-id="SkyMoviesPremiere.uk" tvg-name="Sky Movies Premiere HD 1080\*"
tvg-id="" tvg-name="Sky Cinema Sci-Fi & Horror HD 1080\*"~tvg-id="SkySciFiHorror.uk" tvg-name="Sky Movies Sci-Fi Horror HD"
tvg-id="" tvg-name="Sky Cinema Select HD 1080\*"~tvg-id="Sky Cinema Select UK" tvg-name="Sky Movies Select HD"
tvg-id="" tvg-name="UK BBC NEWS"~tvg-id="" tvg-name="UK BBC NEWS"
tvg-id="" tvg-name="UK :sky 1 HD 1080\*"~tvg-id="Sky1.uk" tvg-name="Sky 1"
tvg-id="" tvg-name="UK :SYFY HD 1080\*"~tvg-id="SCIFI.uk" tvg-name="SyFy"
tvg-id="" tvg-name="UK :Universal Channel HD 1080\*"~tvg-id="" tvg-name="Universal"
tvg-id="" tvg-name="UK :Watch HD 1080\*"~tvg-id="W.uk" tvg-name="Watch"
EOF
#tvg-id="" tvg-name="Sky Sports Action HD 1080\*"~tvg-id="SkySpAction.uk" tvg-name="Sky Sports Action HD"
#tvg-id="" tvg-name="Sky Sports Arena HD 1080\*"~tvg-id="SkySpArena.uk" tvg-name="Sky Sports Arena HD"
#tvg-id="" tvg-name="Sky Sports Cricket HD 1080\*"~tvg-id="SkySpCricket.uk" tvg-name="Sky Sports Cricket HD"
#tvg-id="" tvg-name="Sky Sports F1 HD 1080\*"~tvg-id="SkySpF1.uk" tvg-name="Sky Sports F1 HD"
#tvg-id="" tvg-name="Sky Sports Football HD 1080\*"~tvg-id="SkySpFball.uk" tvg-name="Sky Sports Football HD"
#tvg-id="" tvg-name="Sky Sports Main Event HD 1080\*"~tvg-id="SkySpMainEv.uk" tvg-name="Sky Sports Main Event HD"
#tvg-id="" tvg-name="Sky Sports Mix HD 1080\*"~tvg-id="" tvg-name="Sky Sports Mix HD"
#tvg-id="" tvg-name="Sky Sports News HD 1080\*"~tvg-id="" tvg-name="Sky Sports News HD"
#tvg-id="" tvg-name="Sky Sports PL HD 1080\*"~tvg-id="" tvg-name="Sky Sports PL HD"
#tvg-id="" tvg-name="UK: Alibi HD 1080\*"~tvg-id="" tvg-name="Alibi"
#tvg-id="" tvg-name="UK:Animal Planet HD1080\*"~tvg-id="" tvg-name="Animal Planet HD"
#tvg-id="" tvg-name="uk: BT Sports 2 HD 1080\*"~tvg-id="" tvg-name="BT Sport 2 HD"
#tvg-id="" tvg-name="UK: Comedy Centeral HD1080\*"~tvg-id="" tvg-name="Comedy Central"
#tvg-id="" tvg-name="UK :Crime &Invietgation HD1080\*"~tvg-id="" tvg-name="Crime and Investigation HD"
#tvg-id="" tvg-name="UK: Dave HD1080\*"~tvg-id="" tvg-name="Dave"
#tvg-id="" tvg-name="UK: Discovery HD 1080\*"~tvg-id="" tvg-name="Discovery HD"
#tvg-id="" tvg-name="UK: Eden HD 1080\*"~tvg-id="" tvg-name="Eden"
#tvg-id="" tvg-name="UK:FOX HD 1080\*"~tvg-id="" tvg-name="FOX"
#tvg-id="" tvg-name="UK: Good Food HD1080\*"~tvg-id="" tvg-name="UK: Good Food HD1080\*"
#tvg-id="" tvg-name="UK: H2 HD 1080\*"~tvg-id="" tvg-name="H2"
#tvg-id="" tvg-name="UK :History HD 1080\*"~tvg-id="" tvg-name="History HD"
#tvg-id="" tvg-name="UK: LifeTime HD1080\*"~tvg-id="" tvg-name="LifeTime HD"
#tvg-id="" tvg-name="UK : Sky Arts HD 1080\*"~tvg-id="" tvg-name="Sky Arts"
#tvg-id="" tvg-name="UK: Racing UK HD1080\*"~tvg-id="" tvg-name="Racing UK"
#tvg-id="" tvg-name="UK: National Geographic HD 1080\*"~tvg-id="" tvg-name="National Geographic HD"
#tvg-id="" tvg-name="UK :Nat Geo Wild HD 1080\*"~tvg-id="" tvg-name="Nat Geo Wild HD"
#tvg-id="" tvg-name="UK: Sky Atlantic HD1080\*"~tvg-id="" tvg-name="Sky Atlantic"
#group-title=H264-ACC|"UK: Entertainment"~group-title=H264-ACC|UK: Entertainment

getChannelNumber()
{
  local pattern=$(echo "$*" | sed 's/\*/\\*/')
  local num=$(grep -ne "^$pattern\$" ${CHANNELS} | grep -Eo '^[^:]+')
  [[ $num -eq "" ]] && num=0
  echo $num
}


addchannels()
{
  SERVICE=$1
  URL=$2
  OUTPUT=${XMLTV}/${SERVICE}.m3u
  CHANNELS=${XMLTV}/${SERVICE}.channels

  [[ -f "${CHANNELS}" ]] || touch "${CHANNELS}"

  exec > $OUTPUT
  echo "#EXTM3U"
  curl -s "${URL}" |
  sed '/#EXTM3U/d' |
  sed -e "${sedscript}" |
  while read line
  do
    #channelID=$(echo  $line | sed 's/^.*tvg-name="\([^"]*\)\" .*$/\1/')
    channelID=$(echo  $line | sed  's/.*,\(.*\)$/\1/')
    channel=$(getChannelNumber "${channelID}")
    if [[ $channel = 0 ]] 
    then
      echo ${channelID} >> ${CHANNELS}
      channel=$(getChannelNumber "${channelID}")
    fi

    echo $line |
      sed -e "s/tvg-id/tvh-chnum=\"$channel\" &/" -e 's/group-title="/&H264-AAC|/'
    read line
    echo $line
  done 
}

#echo ${sedscript}

addchannels magic $URL

# vim: nu sw=2 ai
